version: 2
update_configs:
    - automerged_updates: true
updates:
    # Enable version updates for Gradle
    - package-ecosystem: "maven"
      # Look for `pom.xml` in the `root` directory
      directory: "/"
      # Check for updates once daily
      schedule:
          interval: "daily"
