# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JavaFX CI

on:
  push:
    branches:
      - javafx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
      - name : Copy plugin to upload
        run: mkdir software && cp target/*.jar staging
      - name : Upload software
        uses: actions/upload-artifact@v2
        with:
          name: JavaFX GUI
          path: software
